---
- hosts: all
  become: yes
  handlers:
    - name: Import global handlers
      import_tasks: handlers/global_handlers.yml  
  roles:
    - Install_docker
    - SElinux
      #- Firewall
    - Kubernetes
